### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Axkaban** [bahobab/project3-scoop#1]
First of. Passed all 49 tests in 40 milliseconds 👍 

Routes:
[https://github.com/bahobab/project3-scoop/blob/master/server.js#L47-L59](https://github.com/bahobab/project3-scoop/blob/master/server.js#L47-L59)
Great implementation. I know it may feel like a simple task after you grabbed understanding of routes, yet that simplicity becomes really important when keeping track of where will you direct information. 
Later on you will be using a separate file for those routes, and with express, they will have methods related to get, put, and delete.

Functions:

Very well done! 
[https://github.com/bahobab/project3-scoop/blob/master/server.js#L62-L90](https://github.com/bahobab/project3-scoop/blob/master/server.js#L62-L90)
You might have also noticed that they were very alike to the article functions. That is common place in server side programming, the only difference is in the details. Later on each part will have a file on their own, one for articles, one for users and one for comments, then if there are pieces of code that repeat in the different files, like upvote and downvote, they might become a middleware file that you import and use.

**Comment by bahobab** [comment]
Thanks Axel for the review and the heads up regarding middleware. I can see their use in the following lessons.
Thanks again,
Konan
