### ISSUE TITLE
Overall

### ISSUE THREAD

**Issue by Axkaban** [bahobab/project3-scoop#2]
Grade: **Meets expectations and requirements** 
200 OK!

You're ready to implement the bonus. if you were wondering what to use, a good hint can be this library: [node-yaml](https://www.npmjs.com/package/node-yaml)

and if you want to start reading about express structure: [https://www.terlici.com/2014/08/25/best-practices-express-structure.html](https://www.terlici.com/2014/08/25/best-practices-express-structure.html)

Best of luck!

**Comment by bahobab** [comment]
I've started looking into the bonus part. I will try to add it to this project and if possible implement it in the following ones.
Thanks very much Axel for the review and great pointers to the valuable articles.
Konan
